platform :ios, '8.1'
pod 'UIView-Autolayout', '~> 0.2.0'
pod 'MJRefresh', '~> 2.4.7'
pod 'CocoaLumberjack', '~> 2.0.1'
pod 'UIColor+FlatColors', '~> 0.0.2'
pod 'Masonry', '~> 0.6.2'
pod 'MMPlaceHolder', '~> 1.8'
pod 'PureLayout', '~> 3.0.1'
pod 'pop', '~> 1.0.7'
pod 'ReactiveMantle', '~> 0.1.0'
pod 'AFNetworking', '~> 2.6.0'
pod 'GPUImage', '~> 0.1.7'
pod 'VBFPopFlatButton', '~> 0.0.6'
